### ISSUE TITLE
v. 0.1.9.2 fails to launch: `ValueError: Color number is greater than COLORS-1 (7)`

### ISSUE THREAD

**Issue by barracuda156** [grimandgreedy/aria2tui#2]
@grimandgreedy Could you please take a look?

```
Traceback (most recent call last):
                                    File "/opt/local/bin/aria2tui", line 8, in <module>
           sys.exit(main())
                                        ~~~~^^
                                                File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aria2tui/aria2tui_app.py", line 263, in aria2tui
                                    handleAriaStartPromt(stdscr)
                                                                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
                  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aria2tui/aria2tui_app.py", line 199, in handleAriaStartPromt
                  curses.init_pair(1, 253, 232)
                                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
                                                                               ValueError: Color number is greater than COLORS-1 (7).
 ```

This worked with an earlier version, but now it does not.

**Comment by grimandgreedy** [comment]
Hey @barracuda156. It seems to be saying that your terminal only supports colours 8 colours. May I ask which terminal you are using? I have tested the colour scheme on several terminals without problems. I am not sure why your terminal would have such a restricted colour palette. I can likely create a more restrictive theme that will work with such terminals.

**Comment by grimandgreedy** [comment]
I am surprised that the apple terminal has such limited colour support. I don't have a mac to test on but I was able to replicate this crash on my linux virtual terminal (ctrl+alt+Fn) which has a restricted colour pallette, so I should be able to figure out what is going on. I will have a fix in the next couple of days.

**Comment by grimandgreedy** [comment]
@barracuda156 Actually, I just reread your orginal post and you said that in a previous version of aria2tui there was no crash--was that using the apple terminal? If so then the issue may be something else because aria2tui has always used 8-bit colour codes... 

In any case, adding a fallback theme in case of restricted colours seems appropriate and this should fix the issue.

**Comment by barracuda156** [comment]
@grimandgreedy That still fails to launch, unfortunately:
```
Traceback (most recent call last):
                                    File "/opt/local/bin/aria2tui", line 8, in <
module>
           sys.exit(main())
                                        ~~~~^^
                                                File "/opt/local/Library/Framewo
rks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aria2tui/aria2tu
i_app.py", line 263, in aria2tui
                                    handleAriaStartPromt(stdscr)
                                                                    ~~~~~~~~~~~~
~~~~~~~~^^^^^^^^
                  File "/opt/local/Library/Frameworks/Python.framework/Versions/
3.13/lib/python3.13/site-packages/aria2tui/aria2tui_app.py", line 199, in handle
AriaStartPromt
                  curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLACK)
 
 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Am I just doing something wrong or miss some new dependency? I have updated aria2tui and listpick to current versions from pypi.

**Comment by barracuda156** [comment]
@grimandgreedy [Sorry for a delay, no time for anything.] I have got the GUI to start normally by fixing `mlterm` with Cocoa backend.

<img width="1182" height="696" alt="Image" src="https://github.com/user-attachments/assets/b1680665-bbe9-47d4-95da-360d1e2be16e" />

Looks like it is really picky with regard to terminal emulator, but now we have the one which works as expected.

Closing the issue as resolved.

**Comment by grimandgreedy** [comment]
It is good that it is working on mlterm. I know the PowerPC G5 is from 2003 so perhaps it is an issue with curses and/or snow leopard's implementation of the apple terminal for your processor. If you wanted to pinpoint the issue as it pertains to the apple terminal you could try running the python code I put in the previous post. But since it is working on mlterm I don't think there is anything in my code that I can adjust, unfortunately!
